#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("appCompilacao.Resource", IsApplication=true)]

namespace appCompilacao
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04001e
			public const int btnCalc = 2130968606;
			
			// aapt resource value: 0x7f04000e
			public const int btnCamera = 2130968590;
			
			// aapt resource value: 0x7f04001f
			public const int btnDiscador = 2130968607;
			
			// aapt resource value: 0x7f040009
			public const int btnDivisao = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int btnEnviar1 = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int btnEnviar2 = 2130968580;
			
			// aapt resource value: 0x7f04001a
			public const int btnGravar = 2130968602;
			
			// aapt resource value: 0x7f040021
			public const int btnGravarVideo = 2130968609;
			
			// aapt resource value: 0x7f04000a
			public const int btnMulti = 2130968586;
			
			// aapt resource value: 0x7f040014
			public const int btnNavegador = 2130968596;
			
			// aapt resource value: 0x7f04001b
			public const int btnParar = 2130968603;
			
			// aapt resource value: 0x7f040019
			public const int btnSMS = 2130968601;
			
			// aapt resource value: 0x7f040007
			public const int btnSoma = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int btnSub = 2130968584;
			
			// aapt resource value: 0x7f040011
			public const int btnTelefone = 2130968593;
			
			// aapt resource value: 0x7f040020
			public const int btnTirarFoto = 2130968608;
			
			// aapt resource value: 0x7f04001c
			public const int btnTocar = 2130968604;
			
			// aapt resource value: 0x7f04000c
			public const int btnVoltar = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int imgView1 = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int linearLayout1 = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int textView1 = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int textView3 = 2130968582;
			
			// aapt resource value: 0x7f040012
			public const int textView4 = 2130968594;
			
			// aapt resource value: 0x7f04000f
			public const int textView5 = 2130968591;
			
			// aapt resource value: 0x7f040015
			public const int textView6 = 2130968597;
			
			// aapt resource value: 0x7f040017
			public const int textView7 = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int txtDest = 2130968598;
			
			// aapt resource value: 0x7f040013
			public const int txtLink = 2130968595;
			
			// aapt resource value: 0x7f040018
			public const int txtMensagem = 2130968600;
			
			// aapt resource value: 0x7f040010
			public const int txtNum = 2130968592;
			
			// aapt resource value: 0x7f040001
			public const int txtNum1 = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int txtNum2 = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int txtResult = 2130968587;
			
			// aapt resource value: 0x7f04001d
			public const int video = 2130968605;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int frmCalculadoraNum1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int frmCalculadoraNum2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int frmCalculadoraOper = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int frmCamera = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int frmDiscador = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int frmNavegador = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int frmSMS = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int frmVideo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Main = 2130837512;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
